retrieve gaps and bar height dynamically

diff --git a/home/.config/sway.symlink/bin/sway-snap b/home/.config/sway.symlink/bin/sway-snap
--- a/home/.config/sway.symlink/bin/sway-snap
+++ b/home/.config/sway.symlink/bin/sway-snap
@@ -1,10 +1,17 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
+# Make sure to explicitly set bar height in your sway config because it is set to 0 by default
+# This script assumes you are using a bar with id "bar-0"
+# Should probably rewite in python but im too lazy and it just werks™ as-is
+
+[ -z "$1" ] && exit
+
+bar_height="$(swaymsg -t get_bar_config 'bar-0' | jq '.bar_height')"
 monitor_dimensions="$(swaymsg -t get_outputs |
-	jq -r '.. | select(.focused?) | .current_mode | "\(.width)x\(.height)"')"
+    jq -r '.. | select(.focused?) | .current_mode | "\(.width)x\(.height)"')"
 win_param=( $(swaymsg -t get_tree |
-	jq -r '.. | select(.type?) | select(.focused?) | .rect.x, .rect.y, .rect.width, .rect.height, .deco_rect.height') )
-
+    jq -r '.. | select(.type?) | select(.focused?) |
+        .rect.x, .rect.y, .rect.width, .rect.height, .deco_rect.height') )
 
 monitor_width=${monitor_dimensions%x*}
 monitor_height=${monitor_dimensions#*x}
@@ -15,34 +22,25 @@ win_width=${win_param[2]}
 win_height=${win_param[3]}
 deco_height=${win_param[4]}
 
-bar_height=28
-gaps_inner=0
-gaps_outer=0
-
-[ -n "$1" ] && command="$1"
-
-case $command in
-	up)
-		new_y=0
-		;;
-
-	down)
-		new_y=$(( monitor_height - win_height - deco_height - bar_height ))
-		;;
-
-	left)
-		new_x=0
-		new_y=$(( new_y - deco_height - bar_height ))
-		;;
-
-	right)
-		new_x=$(( monitor_width -  win_width ))
-		new_y=$(( new_y - deco_height - bar_height ))
-		;;
-	*)
-		echo "ERROR: $1: No such position" >&2
-		exit 1
-		;;
+case "$1" in
+    up)
+        new_y=$(( bar_height ))
+        ;;
+    down)
+        new_y=$(( monitor_height - win_height - deco_height ))
+        ;;
+    left)
+        new_x=0
+        new_y=$(( new_y - deco_height ))
+        ;;
+    right)
+        new_x=$(( monitor_width -  win_width ))
+        new_y=$(( new_y - deco_height ))
+        ;;
+    *)
+        echo "ERROR: $1: No such position" >&2
+        exit 1
+        ;;
 esac
 
-swaymsg "move position ${new_x} ${new_y}"
+swaymsg "move absolute position ${new_x} ${new_y}"
